import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Myself</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Introduction About Myself
        </h1>

      
      <div className={styles.grid}>

        <p className={styles.description}>
          My name is Fressy Mathebula. I graduated from Tshwane university of technology with national diploma in 
          information technology. I am confident I have the skills, qualities, and the qualifications needed to excel in this role. 
          I am a fast learner, I possess excellent problem solving capabilities and I can manage a significant work load. 
          I am MCSA and MCSD certified. My abilities is that I can work under pressure and in a team content.
          I have four years experience in information technology. And I am looking for an innovation company like this, 
          where I can continue to learn and also add value as I can.   {' '}
          <code className={styles.code}>pages/home.js</code>
        </p>

        <h2>I've worked as junior business analyst and software developer at Khoro, where i was</h2>
        <ul>
          
            <li>Analyze and document business needs and requirements for various clients with an emphasis on customers, enterprise, competitors, and unique value proposition</li>
            <li>Work with business digital systems and e-commerce platforms for various clients</li>
            <li>Manager for cleaning services</li>
            <li>Designing marketing campaigns and posting them in social media platforms using buffer and Facebook suite</li>
            <li>Designing posters and flyers for cleaning services</li>
            <li>Review and update the website using WordPress</li>
            <li>Searching for cleaning services tenders on the supply chain network (SCNet) platform and online</li>
            <li>Writing proposal which replies to the cleaning services tenders</li>
            <li>Writing weekly and monthly reports</li>
            <li>Sending messages to returning customers about our cleaning services.</li>
         
         </ul>

         <h2>I've worked as junior IT specialist at Vodacom, where i was</h2>

         <ul>
          	<li>Facilitator for computer literacy.</li>
          	<li>Developing application.</li>
            <li>Printing, photocopying, scanning and sending emails for employees.</li>
            <li>Teaching learners how to do HTML5 and CSS basic coding and testing the code.</li>
            <li>Downloading and installing software's.</li>
            <li>Controlling the server room.</li>
            <li>Registering learners to Vodacom e-school platform around Giyani.</li>

         </ul>

         <h2>I've worked as software developer intern at ITthynk, where i was</h2>
        <ul>
             <li>Learning Html5, Css3, JavaScript, Mvc (ASP.net), jQuery, APIs JSON, AJAX and Azure.</li>
             <li>Developing mobile applications.</li> 
             <li>Writing Microsoft certificates.</li>
         </ul>
         

         <h2>I've worked as software developer intern at MLab, where I was</h2>
        <ul>
          <li>Designing, installing, testing, developing and maintaining software systems.</li>
          <li>Learning Html5, Css, Angular, Ionic, Javascript, Jquery, APIs, JSON and AJAX</li>
          <li>Creating mobile applications that help businesses to be more efficient and provide a better service, using Html5, Css, Angular, Javascript, Jquery, APIs, JSON, AJAX and Ionic.</li>
        </ul>
        

         <h2>I've worked as business analyst intern at Tshwane university of technology, where I was</h2>
        <ul>
         <li>
            Gathering, analysing and documenting business needs and requirements using the business analyst documentation templates
         </li>
         </ul>
        

        
          <h2>My Core Skills</h2>
         <ul>
          <li>Results-oriented</li>
          <li> Good Interpersonal and communication skills</li>
          <li>Time management skills<li>
          <li>Analytical skills</li>
          <li>Complex problem solving</li>
          <li>Critical thinking</li>
          <li>Creativity</li>
          <li>People management</li>
          <li>Programming skills</li>
          <li>Co-ordinating with teams</li>
          <li>Computer literacy</li>
          <li>Marketing</li>
          <li></li>Resistance to stress</li>
          <li></li>Good manners</li>
         </ul>

        
          <h2>My Achievements</h2>
          <ul>
             <li>Microsoft Certified Solutions Associate (MCSA)</li>
             <li> Microsoft Certified Solutions Developer (MCSD)</li>
             <li>Microsoft 480 - Programming in HTML5 with JavaScript and CSS3</li>
             <li>Microsoft 486 - Developing ASP.NET MVC Web Applications</li>
             <li>Microsoft 487 - Developing Microsoft Azure and Web Services</li>
             <li> Microsoft S2B Work Readiness</li>
          </ul>
          
         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
   </div>
  )
}
